services:
  - type: web
    name: pae-backend
    runtime: go
    region: oregon
    plan: free
    buildCommand: cd backend && go build -tags netgo -ldflags '-s -w' -o ../app
    startCommand: ./app
    envVars:
      - key: PORT
        value: 8080
    envVarGroups:
      - id: pae-env
