services:
  - type: web
    name: pae-backend
    runtime: go
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: go build -tags netgo -ldflags '-s -w' -o ../app ./cmd/api
    startCommand: ../app
    envVars:
      - key: PORT
        value: 8080
